### ISSUE TITLE
Where can find the file "enwiki-20171001-pages-meta-current-withlinks-abstracts" mentioned in "read_fullwiki.py"? 

### ISSUE THREAD

**Issue by Tesla-jiang** [THUDM/CogQA#11]
Where can find the file "enwiki-20171001-pages-meta-current-withlinks-abstracts" mentioned in "read_fullwiki.py"? It looks like it's a json file, but all I found on the wiki were XML files. Is there anything else in between? Or can you give me the link of this file? Thank you for your

**Comment by 1172135979** [comment]
First of all, thank you for your reply. Based on your help, I have used this extracted English wiki corpus to complete the preliminary exploration of the overall process of the model!
Now, I'm trying to build the model based on the wiki corpus in Chinese, but I'm stuck in the original wiki corpus processing step.
Based on the HotpotQA home page information, I downloaded the zhwiki-latest-pages-meta-current.xml.bz2 file, but after using WikiExtractor, I did not get the text with the tag.
I checked the original XML file, and it seemed that there was no external link for other entities in the XML file.
Have you encountered any similar problems? Or do you have any Suggestions for this problem?
Thank you for your help！

**Comment by qibinc** [comment]
@1172135979 

For questions on building a dataset similar to HotpotQA, the right place to ask should be the [hotpotqa repo](https://github.com/hotpotqa/hotpot).

**Comment by 1172135979** [comment]
Ok, thank you very much！
