### ISSUE TITLE
A question about the "process_train.py"

### ISSUE THREAD

**Issue by shuxiaobo** [THUDM/CogQA#12]
hi, I have a question about the "process_train.py"
![image](https://user-images.githubusercontent.com/11539889/64961515-45588a00-d8c8-11e9-9031-181e2903f48a.png)
Why here parameter in find_fact_content function is `sen_num`?

**Comment by Sleepychord** [comment]
Hi,
`def find_fact_content(bundle, title, sen_num):
    for x in bundle['context']:
        if x[0] == title:
            return x[1][sen_num]`
This function is to find out the sentence of supporting facts(title, sen_num).

**Comment by shuxiaobo** [comment]
But why return the last sentence of the supporting fact?

**Comment by Sleepychord** [comment]
Hi, could you describe your question more carefully? Here we just want to find the sentence of a supporting fact. For example, if the context is [["Title", ["sentence0", "sentence1"]], ["xxx", ["xx"]]] , find_fact_content(bundle, "Title", 1) will return "sentence1".

**Comment by shuxiaobo** [comment]
I'm sorry that I didn't describe the question detailly. 
What I mean is that if we want to find a fact sentence from `bundle['context']`, Why do we just return the last sentence which under `title`? Why we desperate the rest of the sentences under this title?
Thanks

**Comment by Sleepychord** [comment]
But we did not return the last sentence. We return the `sen_num`-th sentence. The variable `sen_num` is assigned at https://github.com/THUDM/CogQA/blob/217f0f12819c86413d315abf9d818da05c41cb9d/process_train.py#L76-L78

**Comment by shuxiaobo** [comment]
OK, Sorry I miss that. Thanks very much !
