### ISSUE TITLE
About dump.pkl

### ISSUE THREAD

**Issue by zycdev** [THUDM/CogQA#13]
Hi, 

Considering rigorousness, is `dump.pkl` mentioned in README the Redis dump file? 

In my experiment, I didn't find `dump.pkl`  in the project directory, but I found a `dump.rdb` which is about 2.4GB in redis directory.

Thank you!

**Comment by Sleepychord** [comment]
Hi, @zycdev . I noticed that redis released a new version(5.0) this year(https://raw.githubusercontent.com/antirez/redis/5.0/00-RELEASENOTES) and changed the format, but I think it doesn't matter.

**Comment by zycdev** [comment]
@Sleepychord  Yes, it doesn't matter indeed. I was just afraid of missing an important file, and I have got a reasonable result with the improved version @qibinc provided. Thank you again!
