### ISSUE TITLE
About the framework of GNN

### ISSUE THREAD

**Issue by eyuansu62** [THUDM/CogQA#15]
i found the code of CognitiveGNN model and it seems like you do not use any framework of GNN such as DGI or PyG, So why do you not use any framework cause i think may it can help with speed problem.

**Comment by Sleepychord** [comment]
Thank you for your suggestion, but the bottleneck of speed is bert so it is not neccessary. We just simply implemented the basic GNN.

**Comment by eyuansu62** [comment]
Thanks for your reply
