### ISSUE TITLE
您好，关于段落抽取的问题。

### ISSUE THREAD

**Issue by modongmoqiu** [THUDM/CogQA#16]
您好，我没有太看明白，您关于段落的选择并不是事先选出可能的几个（比如5个10个）的段落在进行推理，而是直接在所有的段落上进行迭代推理吗？

**Comment by Sleepychord** [comment]
你好，请问你这里的段落是span还是paragraph？在hotpotqa中我们只用了每个文档的第一个段落，如果是span……我们通过预测来选择使用哪些段落，不是实现选出的，也不可能枚举完所有span……所以你能清晰地表述一下你的问题吗？

**Comment by modongmoqiu** [comment]
我想问的意思是，怎么在提供的很多段落中，选择出存在golden sentence的那一个段落，进而选择出golden sentence，所以应该是是您说得paragraph

**Comment by modongmoqiu** [comment]
我的理解是，您先定位问题中的一个实体，然后遍历整个知识库寻找关于这个实体相关的段落，用您说的fuzzy match，然后在找段落中的golden sentence，是吗？

**Comment by Sleepychord** [comment]
由于是维基百科，所以直接访问关于那个实体的段落就可以了。当然如果用在其他问题上，就要用如你所说的retrieval的方法。
