### ISSUE TITLE
关于训练结果

### ISSUE THREAD

**Issue by zhawhjw** [THUDM/CogQA#17]
你好，最近尝试跑了一下代码。在没有动任何参数的情况下得出的正确率似乎没有达到paper上说的55%左右，请问是需要动别的什么设置吗？ 还是我可能哪里搞错了？ 训练过程中也没有任何报错 感觉完全没头绪。 下面是我跑出来的结果， 希望大佬能解答

```json
{'f1': 0.08085961805557072, 'joint_recall': 0.015151681770718994, 'joint_prec': 0.031592446116416414, 'em': 0.052397029034436195, 'sp_f1': 0.11114176393041891, 'joint_f1': 0.019395676593513603, 'joint_em': 0.0, 'sp_em': 0.0, 'sp_recall': 0.08090929552104435, 'prec': 0.08201151088389438, 'recall': 0.08718660277950503, 'sp_prec': 0.18284942606347063}
```

**Comment by Sleepychord** [comment]
按照之前其他出现问题的同学最终的原因，通常是1.数据集下错了或者其他原因没有准备好，请核实你的redis database的大小与readme中是否一致2.虽然我没有复现出这个问题，但是据说在一些机器上如果你显卡资源不足不会报错但是无法正常训练……希望你至少有四块以上显卡进行训练，可以参阅之前close的问题。

**Comment by zhawhjw** [comment]
谢谢答疑 最近几天也试着调试了一下 确实如您所说是显卡显存的问题
另外还想问一下 是否可以把preprocess，evaluation和training分开在不同的机器上跑 我在代码里好像看到了有用到bertcache 如果在某台机子training好以后 只是将模型放到另一台机子上会成功evaluation吗?
刚刚试了一下似乎可行 就是想确认一下是否含有不正当操作。

**Comment by Sleepychord** [comment]
嗯，将模型保存起来换机器当然可以啦~
