### ISSUE TITLE
About process_train.py

### ISSUE THREAD

**Issue by tomtang110** [THUDM/CogQA#2]
Hi ming

If you load the hotpot_dev_fullwiki_v1.json in your process_train.py, there is an error occuring.
![屏幕快照 2019-07-05 17 49 01](https://user-images.githubusercontent.com/33299522/60706644-40cd3800-9f4d-11e9-9386-5b58e70156c4.png)

**Comment by Sleepychord** [comment]
Hi, " hotpot_dev_fullwiki_v1.json" is not training data but validation data. This file is to process training data. Do not change the filename in the code.

**Comment by tomtang110** [comment]
Hi
I have run your code and evaluate it, but the result is weird, I am sure that I use the eval() function in  hotpot_dev_fullwiki_v1.json. Could tell me what function you use to eval()?
![屏幕快照 2019-07-08 13 44 40](https://user-images.githubusercontent.com/33299522/60781644-93456900-a186-11e9-8283-d6486c54275d.png)

**Comment by Sleepychord** [comment]
I think this problem can be solved by reading the evaluation codes, which is offered by HotpotQA dataset. It looks like a small error. I am not sure about the exact reason.
