### ISSUE TITLE
Where can I get “wikipedia documents” ? 

### ISSUE THREAD

**Issue by bultiful** [THUDM/CogQA#22]
Hi , Where can I get “wikipedia documents” ? 
 [step 4 of Preprocess ：Run python read_fullwiki.py to load wikipedia documents to redis ]

**Comment by Sleepychord** [comment]
Duplicate of #11 , you can find them in https://hotpotqa.github.io/wiki-readme.html

**Comment by bultiful** [comment]
thx u !
