### ISSUE TITLE
请问下"hotpot_dev_fullwiki_v1_merge.json"文件从哪来？

### ISSUE THREAD

**Issue by ditingdapeng** [THUDM/CogQA#27]
代码中的注释提到，将**另一个相似模型找到的1-hop节点**拆分　hotpot_dev_fullwiki_v1_merge.json，请问另一个相似模型具体指的是什么？

**Comment by Sleepychord** [comment]
我们额外训练了一个专门用来抽取问题跳的bert，结构与文中介绍的一样。

**Comment by ditingdapeng** [comment]
嗷嗷，谢谢大佬得快速回复！

我最近在尝试用您得代码和思路解决中文问答得问题，有什么建议让我得到中文得这个json文件吗，以使得训练过程能够走通

**Comment by Sleepychord** [comment]
啊，最简单的方法是通过自己写的bm25检索。。。毕竟原来基本上也是数据集提供的。发自我的华为手机-------- 原始邮件 --------发件人： Diting <notifications@github.com>日期： 2020年10月27日周二 下午4:09收件人： THUDM/CogQA <CogQA@noreply.github.com>抄送： Sleepy_chord <sj702d5@foxmail.com>, Comment <comment@noreply.github.com>主    题： Re: [THUDM/CogQA] 请问下"hotpot_dev_fullwiki_v1_merge.json"文件从哪来？ (#27)

嗷嗷，谢谢大佬得快速回复！

我最近在尝试用您得代码和思路解决中文问答得问题，有什么建议让我得到中文得这个json文件吗，以使得训练过程能够走通
