### ISSUE TITLE
论文中"提取一跳节点，但是不计算语义向量"的含义

### ISSUE THREAD

**Issue by ditingdapeng** [THUDM/CogQA#28]
"And when extracting 1-hop nodes from question to initialize G, we do not calculate semantic vectors and only the Question part exists in the input."

请问这句话该怎样理解？看论文中系统一在访问节点x的输入为:[CLS] Question [SEP] clues[x,G] [SEP]  Para[x]，不计算语义向量的话，相当于第一次是: [CLS] Question [SEP] [SEP]  Para[x],这个意思吗？

**Comment by Sleepychord** [comment]
不是，这里讲的是，[CLS] Question [SEP]这样的结构抽取出第一跳entity。

**Comment by ditingdapeng** [comment]
懂了，谢谢您的回复


在2020年11月3日 22:39，Sleepy_chord<notifications@github.com> 写道：

不是，这里讲的是，[CLS] Question [SEP]这样的结构抽取出第一跳entity。
