### ISSUE TITLE
数据集中的答案并不是来源于该条数据的材料--问题

### ISSUE THREAD

**Issue by ditingdapeng** [THUDM/CogQA#30]
注意到：数据集中的答案并不是来源于该条数据的材料，那么多跳是根据什么来跳的？不是本条数据的材料吗？

例如：问题-Which magazine was started first Arthur's Magazine or First for Women?，答案是Arthur's Magazine，但是答案在"context"中没有提到。

排除了用wipidia的外部数据进行多跳，因为窝并没有运行那段程序，嗷嗷

**Comment by Sleepychord** [comment]
如果是训练集肯定提到了，你再仔细看一下……对于测试open domain情况，是要从wiki中逐步抽取，第一步的检索可能查不到。
