### ISSUE TITLE
代码中utils中的GENERAL_WD解释

### ISSUE THREAD

**Issue by ditingdapeng** [THUDM/CogQA#31]
在process_train中对数据进行处理时，utils.py的认知图构建，这个变量的含义具体指的什么意思？

如下：
GENERAL_WD = ['is', 'are', 'am', 'was', 'were', 'have', 'has', 'had', 'can', 'could',  'shall', 'will', 'should', 'would', 'do', 'does', 'did', 'may', 'might', 'must', 'ought', 'need', 'dare']

另外我能否理解为process_train做的工作就是加一个模糊匹配的实体，以及构建认知图?
感谢回复~

**Comment by Sleepychord** [comment]
一般疑问句的疑问词，一般疑问句用yes no回答。可以这么理解
