### ISSUE TITLE
Where can i get `hotpot_train_v1.1.json`?

### ISSUE THREAD

**Issue by daniildiveev** [THUDM/CogQA#39]
When i run `!python /content/CogQA/process_train.py` the following error occures:

` Traceback (most recent call last):
 File "/content/CogQA/process_train.py", line 18, in <module>`

`with open('./hotpot_train_v1.1.json', 'r') as fin:`

`FileNotFoundError: [Errno 2] No such file or directory: './hotpot_train_v1.1.json'  `

I wonder where can i get this file, please help

**Comment by Sleepychord** [comment]
http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_train_v1.1.json
