### ISSUE TITLE
About process_train.py

### ISSUE THREAD

**Issue by Yarkona** [THUDM/CogQA#4]
Hi, Ming
According to README, I run the code in the following order:
1) process_train.py with hotpot_train_v1.1.json  -> get hotpot_train_v1.1_refined3.json
2) read_fullwiki.py ( from read_fullwiki.ipynb)
3) run_cg.py  (first time) 
4) run_cg.py (second time, set lr=4*1e-5)  -> models/bert-base-uncased.bin & .bin.tmp
5) eval_cg.py on hotpot_dev_fullwiki_v1.json -> hotpot_dev_fullwiki_v1_pred.json
6) hotpot_evaluate_v1.py with  hotpot_dev_fullwiki_v1_pred.json & hotpot_dev_fullwiki_v1.json
the results not ideal, but I can not find any reasons.
Some wrong operations  exist during the above process?
Some Other questions
1)In step 1,   GOT hotpot_train_v1.1_refined3.json.  By using "_id", I SELECT   the same 500 examples as hotpot_train_v1.1_500_refined.example.json from hotpot_train_v1.1_refined3.json.
but there are some differences between the new_generated 500 and your provided 500 examples.  
2) In read_fullwiki.py, the last part,  "pages" represent ? 
Could you please give me some advice? Or could you provide a refined-training dataset download link? Thanks a lot!

**Comment by Sleepychord** [comment]
I am sorry for the messes puzzling you... I am working for a detailed version.
6.7. are not important, just out-of-date codes.
In the preview code I just use the first 500 samples(as an example). you can delete [:500] in run_cg.py.

**Comment by Yarkona** [comment]
I got it ! Thank you!
